/* Bar functionality */
#include "bar_indicators.h"
#include "bar_tagicons.h"

#include "bar_dwmblocks.h"
#include "bar_ewmhtags.h"
#include "bar_ltsymbol.h"
#include "bar_status.h"
#include "bar_status2d.h"
#include "bar_statuscmd.h"
#include "bar_tags.h"
#include "bar_taggrid.h"
#include "bar_wintitle.h"
#include "bar_flexwintitle.h"
#include "bar_wintitle_hidden.h"
#include "bar_awesomebar.h"
#include "bar_systray.h"
#include "bar_wintitleactions.h"

/* Other patches */
#include "attachx.h"
#include "cfacts.h"
#include "cyclelayouts.h"
#include "dragcfact.h"
#include "dragmfact.h"
#include "fakefullscreenclient.h"
#include "floatpos.h"
#include "focusadjacenttag.h"
#include "focusmaster.h"
#include "keymodes.h"
#include "killunsel.h"
#include "moveresize.h"
#include "pertag.h"
#include "push_no_master.h"
#include "reorganizetags.h"
#include "restartsig.h"
#include "scratchpad.h"
#include "scratchpad_alt_1.h"
#ifdef XINERAMA
#include "sortscreens.h"
#endif // XINERAMA
#include "sticky.h"
#include "swallow.h"
#include "swapfocus.h"
#include "swaptags.h"
#include "switchcol.h"
#include "tagallmon.h"
#include "tagothermonitor.h"
#include "tagswapmon.h"
#include "togglefullscreen.h"
#include "transfer.h"
#include "unfloatvisible.h"
#include "vanitygaps.h"
#include "warp.h"
#include "zoomswap.h"
/* Layouts */
#include "layout_flextile-deluxe.h"
