/* Bar functionality */
#include "bar_indicators.c"
#include "bar_tagicons.c"

#include "bar_dwmblocks.c"
#include "bar_ewmhtags.c"
#include "bar_ltsymbol.c"
#include "bar_status.c"
#include "bar_status2d.c"
#include "bar_statuscmd.c"
#include "bar_tags.c"
#include "bar_taggrid.c"
#include "bar_wintitle.c"
#include "bar_flexwintitle.c"
#include "bar_wintitle_hidden.c"
#include "bar_awesomebar.c"
#include "bar_systray.c"
#include "bar_wintitleactions.c"

/* Other patches */
#include "attachx.c"
#include "cfacts.c"
#include "cyclelayouts.c"
#include "dragcfact.c"
#include "fakefullscreenclient.c"
#include "floatpos.c"
#include "focusadjacenttag.c"
#include "focusmaster.c"
#include "keymodes.c"
#include "killunsel.c"
#include "moveresize.c"
#include "pertag.c"
#include "push_no_master.c"
#include "reorganizetags.c"
#include "restartsig.c"
#include "scratchpad.c"
#include "scratchpad_alt_1.c"
#ifdef XINERAMA
#include "sortscreens.c"
#endif // XINERAMA
#include "sticky.c"
#include "swallow.c"
#include "swapfocus.c"
#include "swaptags.c"
#include "switchcol.c"
#include "tagallmon.c"
#include "tagothermonitor.c"
#include "tagswapmon.c"
#include "togglefullscreen.c"
#include "transfer.c"
#include "unfloatvisible.c"
#include "vanitygaps.c"
#include "warp.c"
#include "zoomswap.c"
#include "dragmfact.c"
/* Layouts */
#include "layout_flextile-deluxe.c"
